Server:
  http://192.168.0.27:1004/into/carEnterParkLotJY
MySQL:
  database: {'host': '192.168.1.127', 'port': 3306, 'user': 'root', 'password': '123456', 'dbname': 'park_ell', 'charset': 'utf8'}
  sql: {'query': {}, 'update': {}}
File:
  path: F:/InterfaceAutomation/casedata.xlsx
Email:
  host: 'smtp.163.com'
  port: 465
  passwd: 'YZZNFHGRPVEVGENC'
  sender: 'x1124292446@163.com'
  receivers: 'x1124292446@163.com'
  content: '来自testeraj的测试报告，请查收！ps：详情见附件'
Log:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(levelname)s: %(message)s'
  handlers:
    attribute:
      class: logging.FileHandler
      filename: ./Logs/log.log
      mode: a
      level: DEBUG
      formatter: simple
      encoding: utf-8
  loggers:
    simpleExample:
      level: NOTSET
      handlers: [attribute]
      propagate: yes
  root:
    level: NOTSET
    handlers: [attribute]