Server:
  http://192.168.0.27:1004/into/carEnterParkLotJY
MySQL:
  database: {'host': '127.0.0.1', 'port': 3306, 'user': 'root', 'password': '123456', 'dbname': 'milor', 'charset': 'utf-8'}
  sql: {'query': {}, 'update': {}}
File:
  path: test.xlsx
Log:
  version: 1
  formatters:
    simple:
      format: '%(asctime)s - %(levelname)s: %(message)s'
  handlers:
    attribute:
      class: logging.FileHandler
      filename: ./Logs/log.log
      mode: a
      level: DEBUG
      formatter: simple
      encoding: utf-8
  loggers:
    simpleExample:
      level: NOTSET
      handlers: [attribute]
      propagate: yes
  root:
    level: NOTSET
    handlers: [attribute]